### ISSUE TITLE
No root prompt

### ISSUE THREAD

**Issue by Lumpusz** [moonlight-stream/moonlight-docs#86] opened 2018-01-13 11:05 UTC
Hi,

I have installed Moonlight for rooted devices from Play store, and I get no root prompt, despite my phone is rooted. Mouse capture still acts very strange. Is there any way to force the prompt? When should it pop up?

Thanks

EDIT:
My client is Android 7.1 (Lineage OS), Oneplus ONE, rooted with Magisk

**Comment by cgutman** [comment] 2018-01-16 04:35
It should try to use `su` when the stream starts. Can you try to get a logcat log from your device when trying to stream?

**Comment by Lumpusz** [comment] 2018-01-16 09:00
Sure, np. Here is the log. While streaming, I had a bluetooth mouse connected to the phone. Cheers.
[logcat.log](https://github.com/moonlight-stream/moonlight-docs/files/1634245/logcat.log)

**Comment by cgutman** [comment] 2018-01-16 09:45
OK, the bug is caused by Moonlight detecting that the NVIDIA mouse capture API is available. This is normally only true for Shield devices running the official firmware. If this is available, we prefer it because it allows us to capture without root.

Unfortunately, this API was stubbed out in LineageOS for a badly behaving app such that it breaks well-behaved apps like Moonlight that detect the feature "properly" (using reflection to avoid crashing) and change their behavior based on whether it is present. Moonlight detects the method's availability and tries to hide the cursor with it, but since it's not really there, nothing happens when we call it.

This is the offending commit: https://github.com/LineageOS/android_frameworks_base/commit/d304f478a023430f4712dbdc3ee69d9ad02cebd3

**Comment by Lumpusz** [comment] 2018-01-16 09:55
Any way to fix/workaround the problem? E.g.
```
if (isLineageOS()) {
    promptForRoot();
} else {
    checkNvidiaApi();
}
```

**Comment by cgutman** [comment] 2018-01-20 10:32
Fixed by https://github.com/moonlight-stream/moonlight-android/commit/e4c251e7ee049ec34ec1c497a1556378361b9815

**Closed by cgutman** 2018-01-20 10:32 UTC
