### ISSUE TITLE
Mouse issue Chrome Plugin

### ISSUE THREAD

**Issue by GeneralCaos** [moonlight-stream/moonlight-docs#75] opened 2017-12-03 04:50 UTC
When I add Windows 10 to stream, the mouse likes to jump around

**Comment by cgutman** [comment] 2017-12-03 08:14
This is a Chrome bug. Duplicate of https://github.com/moonlight-stream/moonlight-chrome/issues/353

You'll find a build with a workaround in that issue.

**Closed by cgutman** 2017-12-03 08:14 UTC
